### ISSUE TITLE
Error when using latest version of tws

### ISSUE THREAD

**Issue by codingsett** [erdewit/tws_async#10]
Hello I installed tws gateway the latest version and after installation when i run my bot i get this

`Traceback (most recent call last):
  File "bottrader.py", line 1, in <module>
    from ib_insync import *
  File "/usr/local/lib/python3.5/dist-packages/ib_insync/__init__.py", line 14
    f'Old version ({ibapi.__version__}) of ibapi package detected. '`

What might be the issue?

**Comment by erdewit** [comment]
Like the error message says, it's the ibapi package that is too old (not TWS).
