### ISSUE TITLE
tws_async.py getting Connection lost

### ISSUE THREAD

**Issue by sleepykid** [erdewit/tws_async#2]
Thanks for this example.  I was able to run the ipynb version with no issues but trying to run tws_async.py getting 'Connection lost'

On the IB Gateway Log it shows: 
....
....
Start API message, ClientID=1
Ignoring API request 'jextend.a1' since API is not accepted.
Terminating async queue.
...
...

any advice would be great, thanks!

**Comment by erdewit** [comment]
If this is on Windows then it is a known issue with reconnecting; The tws_async_windows.py script bypasses the issue.

**Comment by sleepykid** [comment]
on mac osx El Capitan

**Comment by sleepykid** [comment]
I also tried the tws_async_windows.py but also same log error in IB Gateway and console message:
<_SelectorSocketTransport fd=89 read=idle write=<idle, bufsize=0>>
Connection lost None <_SelectorSocketTransport closing fd=89 read=idle write=<idle, bufsize=0>>

**Comment by erdewit** [comment]
Try with a different clientId.

**Comment by sleepykid** [comment]
same issue, I also did run the pip install --upgrade PyQt5 quamash
(running python 3.6)

**Comment by erdewit** [comment]
Can you restart the gateway?

**Comment by herrold** [comment]
I took this message from the initial report:
   Ignoring API request 'jextend.a1' since API is not accepted.

to indicate that either the API was not enabled, or that a connection was being attempted from other than the localhost, and so the initial connection was failing

**Comment by sleepykid** [comment]
ok,
 I re-started and it still doesn't work. ( IB Gateway 964 )
in the IB Gateway log, it is 
Server version 120
Client version 120

Definitely using localhost:
tws.connect(loop, host='localhost', port=4002, clientId=99)

**Comment by erdewit** [comment]
I will look further into it but have no clue what could be different on OSX and no way of testing.

The strange thing is that the notebook works for you. Btw you can also use the IB supplied sample scripts.

**Comment by sleepykid** [comment]
ok thanks, I think because the notebook version uses PyQt5.QtNetwork whereas tws_async.py doesn't

**Comment by erdewit** [comment]
I've tested it with an image of OS X 10.11.6 and could reproduce the issue.
The issue is caused by the "::1 localhost" IPv6 alias in the /etc/hosts file.
 It can be solved by using '127.0.0.1' instead of 'localhost' in the connect call.

Note that this would apply to the IB supplied sample files as well.
