### ISSUE TITLE
tws_async with concurrent.futures

### ISSUE THREAD

**Issue by viper2017** [erdewit/tws_async#4]
@erdewit 

Compliments for the code! Instead running one TWS connection with one thread, I'd like to have more than one TWS instance (each one able to pass orders and downloading market data independently); ideally running in different processes but at the same time able to pass results between processes by using one of the IPC solutions. I have tried, without success, three solutions:
1. wrap the each TWS_async in one process with multiprocessing.Process, it works but it is impossible to pass the data from one process to another. I tried with Manager, Queue, Listener/Client, etc... it seems that each async event loop is ring-fenced.
2. Then I tried using concurrent.futures with ProcessPoolExecutor but actually didn't open a new process. Instead, nevertheless the error, it runs the two different TWS requests in a unique thread (as expected from async). Of course, in this case passing data between the two TWSs is trivial.
3. In addition, I need to connect one TWS only at specific time, so I tried to use the apscheduler.scheduler.asyncio, but without success.
Let me know if you want to see the code for the cases above.
Do you have an idea how to modify your code in order to able to launch a second TWS with concurrent.future in another process and to use apscheduler?
Many Thanks in advance

**Comment by erdewit** [comment]
If you keep it in one process then it is super easy to use multiple TWS clients:

```python
import asyncio
from tws_async import TWSClient


class TWS1(TWSClient):
    def __init__(self):
        TWSClient.__init__(self)

    def connectAck(self):
        self.reqAccountUpdates(1, '')

    def updateAccountValue(self, key, val, currency, accountName):
        print('Account 1 update: {} = {} {}'.format(key, val, currency))


class TWS2(TWSClient):
    def __init__(self):
        TWSClient.__init__(self)

    def connectAck(self):
        self.reqAccountUpdates(1, '')

    def updateAccountValue(self, key, val, currency, accountName):
        print('Account 2 update: {} = {} {}'.format(key, val, currency))


tws1 = TWS1()
tws2 = TWS2()
tws1.connect(host='127.0.0.1', port=7497, clientId=1)
tws2.connect(host='127.0.0.1', port=7497, clientId=2)
loop = asyncio.get_event_loop()
loop.run_forever()
```

**Comment by viper2017** [comment]
@erdewit 
Thanks for the prompt answer, but I need to run tws2 in another process because I need to download some different data in **parallel**, doing some calculations on these data and return results to the main process that never stops downloading the other data. I have to figure out why the concurrent.futures ProcessPoolExecutors does not work here... AsyncIO module does allow to run some other task in parallel in another thread/process.
In addition, I have to schedule the tws2 to run only at some point of the day for every day, I tried to use the apscheduler module but it was ignored. I think for the same reason of the above. 
Many Thanks anyway.
Regards
V.

**Comment by erdewit** [comment]
tws1 and tws2 will download different data at the same time with no problem. If the calculation takes a short time (say a few ms) you can let it run in the same process too.

I don't know about apscheduler, the docs say it should work with asyncio. But it's easy to schedule anything yourself. There is loop.call_later or it can be done in a coroutine. Here is an example of the latter, it also shows how to run a long calculation in a separate process pool:

```python
import asyncio
import time
import math
from concurrent.futures import ProcessPoolExecutor
from tws_async import TWSClient

loop = asyncio.get_event_loop()
executor = ProcessPoolExecutor(1)


class TWS1(TWSClient):
    def __init__(self):
        TWSClient.__init__(self)

    def connectAck(self):
        self.reqAccountUpdates(1, '')

    def updateAccountValue(self, key, val, currency, accountName):
        print('Account 1 update: {} = {} {}'.format(key, val, currency))


class TWS2(TWSClient):
    def __init__(self):
        TWSClient.__init__(self)

    def connectAck(self):
        self.reqAccountUpdates(1, '')

    def updateAccountValue(self, key, val, currency, accountName):
        print('Account 2 update: {} = {} {}'.format(key, val, currency))


def bigCalculation(n):
    x = 0
    i = 1
    t = time.time()
    while time.time() - t < 0.5:
        x += math.sin(n / i)
        i += 1
    return x


async def scheduler():
    n = 0
    while True:
        result = await loop.run_in_executor(executor, bigCalculation, n)
        print(result)
        await asyncio.sleep(0.5)
        n += 1


tws1 = TWS1()
tws2 = TWS2()
tws1.connect(host='127.0.0.1', port=7497, clientId=1)
tws2.connect(host='127.0.0.1', port=7497, clientId=2)
loop.create_task(scheduler())
loop.run_forever()
```

**Comment by viper2017** [comment]
@erdewit 
your code works well, but if you try to start a second connection in the loop.run_in_executor doesn't work (same error when I try to launch the 2nd connection by apscheduler.asyncio...)
I am still investigating on this and I'll let you know.
BTW,
Thank you very much for your help! the tws_async is incredible faster the the IBAPI!
where are you based?

**Comment by erdewit** [comment]
Glad it works faster for you. But I'm not sure why you're intent on running the second client in a separate process; There is absolutely no need for it. The easiest thing is to use one event loop to rule them all.

Btw  I'm in The Hague in the Netherlands.
