### ISSUE TITLE
ERROR 0 504 Not connected

### ISSUE THREAD

**Issue by paulperry** [erdewit/tws_async#5]
I'd like to just use the tws_async.py and asyncio.  I ran tws.ipnb and it works.  I then modified it by commenting out the `%gui qt5` and changed the : 
`from tws_async_qt import TWSClient, iswrapper`
tp
`from tws_async import TWSClient, iswrapper`
Now I get a : 
`ERROR:root:ERROR 0 504 Not connected`
on the tws.reqHistoricalData' api call.

I was expecting it would work.  I'm on a Mac OS X 12.10.5 , and anaconda3 with python 3.5.2 . 
Am I missing something?

**Comment by erdewit** [comment]
Straight asyncio in general doesn't work in a notebook. Something is needed to integrate the asyncio event loop with the Jupyter kernel. The notebook example uses the Qt event loop for that and it can't just be ripped out.
